version: "3"
services:
  db:
    image: mdillon/postgis:9.6-alpine
    environment: 
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: kelvin
      POSTGRES_DB: landsat8
    volumes:
      - "/data/big/repos/dump:/var/run/"
      - "/data/fast/thermal_alert:/var/lib/postgresql/data"
    ports:
        - "9001:5432"
  admin:
      image: jlaura/pgadmin4:0.2
      ports:
      - "9002:5050"
